# Generated by Django 4.2 on 2024-07-28 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateModified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modifiedByModelName', models.CharField(blank=True, max_length=100, null=True)),
                ('modifiedBymodelId', models.CharField(blank=True, max_length=10, null=True)),
                ('modelName', models.CharField(blank=True, max_length=100, null=True)),
                ('modelId', models.CharField(blank=True, max_length=10, null=True)),
                ('fieldName', models.CharField(blank=True, max_length=100, null=True)),
                ('fieldType', models.CharField(blank=True, max_length=100, null=True)),
                ('oldValue', models.CharField(blank=True, max_length=200, null=True)),
                ('newValue', models.CharField(blank=True, max_length=200, null=True)),
                ('isInActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateModified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emailId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('r', "Regular - Can't delete members"), ('a', 'Admin - Can delete members')], default='r', max_length=10)),
                ('imageUrl', models.CharField(max_length=200)),
                ('isInActive', models.BooleanField(default=False)),
            ],
        ),
    ]
